const FILTERS = Object.freeze({
  categories: [
    {
      name: "Car",
      value: "Car",
      checked: false,
      filterKey: "nft_category",
    },
    {
      name: "Land",
      value: "Land",
      checked: false,
      filterKey: "nft_category",
    },
    {
      name: "Building",
      value: "Building",
      checked: false,
      filterKey: "nft_category",
    },
  ],
  subCategories: [
    {
      name: "Common",
      value: "COMMON",
      checked: false,
      filterKey: "nft_collection",
    },
    {
      name: "Rare",
      value: "RARE",
      checked: false,
      filterKey: "nft_collection",
    },
    {
      name: "Legendary",
      value: "LEGENDARY",
      checked: false,
      filterKey: "nft_collection",
    },
    {
      name: "Alien",
      value: "ALIEN",
      checked: false,
      filterKey: "nft_collection",
    },
    {
      name: "Immortal",
      value: "IMMORTAL",
      checked: false,
      filterKey: "nft_collection",
    },
  ],
  landSubCategories: [
    {
      name: "Downtown",
      value: "DOWNTOWN",
      checked: false,
      filterKey: "nft_collection",
    },
    {
      name: "Mainland",
      value: "MAINLAND",
      checked: false,
      filterKey: "nft_collection",
    },
    {
      name: "Prime",
      value: "PRIME",
      checked: false,
      filterKey: "nft_collection",
    },
    {
      name: "Heart",
      value: "HEART",
      checked: false,
      filterKey: "nft_collection",
    },
  ],
  buildingSubCategories: [
    {
      name: "Silver",
      value: "SILVER",
      checked: false,
      filterKey: "nft_collection",
    },
    {
      name: "Gold",
      value: "GOLD",
      checked: false,
      filterKey: "nft_collection",
    },
    {
      name: "Platinum",
      value: "PLATINUM",
      checked: false,
      filterKey: "nft_collection",
    },
    {
      name: "Diamond",
      value: "DIAMOND",
      checked: false,
      filterKey: "nft_collection",
    },
  ],
  carCategories: [
    {
      name: "Tuner",
      value: "Tuner",
      checked: false,
      filterKey: "car_category",
    },
    {
      name: "Battle",
      value: "Battle",
      checked: false,
      filterKey: "car_category",
    },
    {
      name: "Vintage",
      value: "Vintage",
      checked: false,
      filterKey: "car_category",
    },
    {
      name: "Super",
      value: "Super",
      checked: false,
      filterKey: "car_category",
    },
    {
      name: "Hyper",
      value: "Hyper",
      checked: false,
      filterKey: "car_category",
    },
    {
      name: "Concept",
      value: "Concept",
      checked: false,
      filterKey: "car_category",
    },
  ],
  carModels: [
    {
      name: "Streetdon",
      value: "Streetdon",
      checked: false,
      filterKey: "car_model",
    },
    {
      name: "Stallion",
      value: "Stallion",
      checked: false,
      filterKey: "car_model",
    },
    {
      name: "Mauler",
      value: "Mauler",
      checked: false,
      filterKey: "car_model",
    },
    {
      name: "Fightcat",
      value: "Fightcat",
      checked: false,
      filterKey: "car_model",
    },
    {
      name: "Classico",
      value: "Classico",
      checked: false,
      filterKey: "car_model",
    },
    {
      name: "Macho",
      value: "Macho",
      checked: false,
      filterKey: "car_model",
    },
    {
      name: "Royale",
      value: "Royale",
      checked: false,
      filterKey: "car_model",
    },
    {
      name: "Toro GT",
      value: "Toro GT",
      checked: false,
      filterKey: "car_model",
    },
    {
      name: "Hypra GT",
      value: "Hypra GT",
      checked: false,
      filterKey: "car_model",
    },
    {
      name: "Squadra GT",
      value: "Squadra GT",
      checked: false,
      filterKey: "car_model",
    },
    {
      name: "Jaws",
      value: "Jaws",
      checked: false,
      filterKey: "car_model",
    },
    {
      name: "Concept X",
      value: "Concept X",
      checked: false,
      filterKey: "car_model",
    },
  ],
  bodySurface: [
    {
      name: "Glossy",
      value: "Glossy",
      checked: false,
      filterKey: "body_surface",
    },
    {
      name: "Matte",
      value: "Matte",
      checked: false,
      filterKey: "body_surface",
    },
  ],
  level: [
    {
      name: "Level 1",
      value: "1",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 2",
      value: "2",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 3",
      value: "3",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 4",
      value: "4",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 5",
      value: "5",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 6",
      value: "6",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 7",
      value: "7",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 8",
      value: "8",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 9",
      value: "9",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 10",
      value: "10",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 11",
      value: "11",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 12",
      value: "12",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 13",
      value: "13",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 14",
      value: "14",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 15",
      value: "15",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 16",
      value: "16",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 17",
      value: "17",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 18",
      value: "18",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 19",
      value: "19",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 20",
      value: "20",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 21",
      value: "21",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 22",
      value: "22",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 23",
      value: "23",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 24",
      value: "24",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 25",
      value: "25",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 26",
      value: "26",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 27",
      value: "27",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 28",
      value: "28",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 29",
      value: "29",
      checked: false,
      filterKey: "nft_level",
    },
    {
      name: "Level 30",
      value: "30",
      checked: false,
      filterKey: "nft_level",
    },
  ],
  saleType: [
    {
      name: "Bid",
      value: "bid",
      checked: false,
      filterKey: "sale_type",
    },
    {
      name: "Buy",
      value: "buy",
      checked: false,
      filterKey: "sale_type",
    },
  ],
  saleKind: [
    {
      name: "Timed Auction",
      value: "timed_auction",
      checked: false,
      filterKey: "sale_kind",
    },
    {
      name: "Listed for sale",
      value: "onsale",
      checked: false,
      filterKey: "sale_kind",
    },
    {
      name: "Not on sale",
      value: "not_on_sale",
      checked: false,
      filterKey: "sale_kind",
    },
  ],
  showCarCategories: true,
  showSubCategories: true,
  showCarModels: true,
  showBodySurface: true,
  showOthers: true,
  showLevel: true,
  showSaleType: true,
  showSaleKind: true,
  showAuction: true,
});

export default FILTERS;
